export const MusicData = [
  {
    "id": 1,
    "title": "Technology",
    "subtitle": "",
    "release_date": "2014-4-19",
    "length": 286,
    "keysig": ["A / F#m"],
    "tempo": [175],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-technology",
    "art": "https://f4.bcbits.com/img/a2602584825_10.jpg",
  },
  {
    "id": 2,
    "title": "Feel The Buzz",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2014-7-19",
    "length": 252,
    "keysig": ["E / C#m"],
    "tempo": [105, 175],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/sub-sound-feel-the-buzz",
    "art": "https://i1.sndcdn.com/artworks-000201108064-pbjh4c-original.jpg",
  },
  {
    "id": 3,
    "title": "Cyborg Meltdown",
    "subtitle": "",
    "release_date": "2014-7-21",
    "length": 259,
    "keysig": ["D / Bm"],
    "tempo": [110],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-cyborg",
    "art": "https://f4.bcbits.com/img/a1515047272_10.jpg",
  },
  {
    "id": 4,
    "title": "Boom!",
    "subtitle": "",
    "release_date": "2014-7-29",
    "length": 217,
    "keysig": ["C / Am"],
    "tempo": [130],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-boom-the",
    "art": "https://f4.bcbits.com/img/a2416192760_10.jpg",
  },
  {
    "id": 5,
    "title": "Snowball Fight",
    "subtitle": "",
    "release_date": "2014-8-18",
    "length": 232,
    "keysig": ["G / Em"],
    "tempo": [175],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-snowball-fight",
    "art": "https://f4.bcbits.com/img/a3465120814_10.jpg",
  },
  {
    "id": 6,
    "title": "Jubilant Skydive",
    "subtitle": "",
    "release_date": "2014-9-15",
    "length": 264,
    "keysig": ["F / Dm", "G / Em"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-jubilant",
    "art": "https://f4.bcbits.com/img/a2758000269_10.jpg",
  },
  {
    "id": 7,
    "title": "Interstellar",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2014-11-2",
    "length": 206,
    "keysig": ["G / Em"],
    "tempo": [170],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/laszlo-interstellar-similar",
    "art": "https://i1.sndcdn.com/artworks-000201108680-1972jr-original.jpg",
  },
  {
    "id": 8,
    "title": "Radiation",
    "subtitle": "",
    "release_date": "2014-11-21",
    "length": 248,
    "keysig": ["C / Am"],
    "tempo": [174],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-radiation",
    "art": "https://f4.bcbits.com/img/a4080141869_10.jpg",
  },
  {
    "id": 9,
    "title": "When You Sleep",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2014-12-23",
    "length": 211,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/vau-boy-when-you-sleep-2014-ft",
    "art": "https://i1.sndcdn.com/artworks-000201108789-sbmywn-original.jpg",
  },
  {
    "id": 10,
    "title": "I'm Here",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2015-6-12",
    "length": 208,
    "keysig": ["B / G#m"],
    "tempo": [170],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/im-here-remix",
    "art": "https://i1.sndcdn.com/artworks-000201108920-ha9ybf-original.jpg",
  },
  {
    "id": 11,
    "title": "The Time Traveller",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2015-12-12",
    "length": 235,
    "keysig": ["A / F#m"],
    "tempo": [140, 175],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/getsix-the-time-traveller-similar-outskirts-remix",
    "art": "https://i1.sndcdn.com/artworks-000201109218-vmy3sr-original.jpg",
  },
  {
    "id": 12,
    "title": "Epiphany",
    "subtitle": "",
    "release_date": "2015-12-31",
    "length": 221,
    "keysig": ["A / F#m"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/epiphany",
    "art": "https://f4.bcbits.com/img/a4246737652_10.jpg",
  },
  {
    "id": 13,
    "title": "Senses Overload",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2016-1-23",
    "length": 259,
    "keysig": ["F# / D#m"],
    "tempo": [174],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/senses-overload-remix",
    "art": "https://i1.sndcdn.com/artworks-000201109366-dwo6l9-original.jpg",
  },
  {
    "id": 14,
    "title": "Blast Off",
    "subtitle": "",
    "release_date": "2016-2-13",
    "length": 214,
    "keysig": ["C / Am"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/blast-off",
    "art": "https://f4.bcbits.com/img/a0732027681_10.jpg",
  },
  {
    "id": 15,
    "title": "Choreography",
    "subtitle": "",
    "release_date": "2016-5-7",
    "length": 273,
    "keysig": ["D / Bm"],
    "tempo": [145],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-choreography-1",
    "art": "https://f4.bcbits.com/img/a2071563971_10.jpg",
  },
  {
    "id": 16,
    "title": "Whiplash",
    "subtitle": "",
    "release_date": "2016-5-7",
    "length": 229,
    "keysig": ["B / G#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-whiplash-1",
    "art": "https://f4.bcbits.com/img/a2071563971_10.jpg",
  },
  {
    "id": 17,
    "title": "Awake and Unafraid",
    "subtitle": "",
    "release_date": "2016-5-7",
    "length": 227,
    "keysig": ["A / F#m"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-awake-and-unafraid",
    "art": "https://f4.bcbits.com/img/a2071563971_10.jpg",
  },
  {
    "id": 18,
    "title": "Roller Coaster",
    "subtitle": "",
    "release_date": "2016-5-7",
    "length": 262,
    "keysig": ["A / F#m"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-roller-coaster",
    "art": "https://f4.bcbits.com/img/a2071563971_10.jpg",
  },
  {
    "id": 19,
    "title": "Apollo",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2016-6-4",
    "length": 245,
    "keysig": ["A# / Gm"],
    "tempo": [145],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/apollo-remix",
    "art": "https://i1.sndcdn.com/artworks-000201109476-uls3g6-original.jpg",
  },
  {
    "id": 20,
    "title": "Alone",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2016-6-30",
    "length": 242,
    "keysig": ["D / Bm"],
    "tempo": [105],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/alone-remix",
    "art": "https://i1.sndcdn.com/artworks-000201109531-mtar1e-original.jpg",
  },
  {
    "id": 21,
    "title": "Thunderbolt",
    "subtitle": "",
    "release_date": "2016-10-8",
    "length": 278,
    "keysig": ["A# / Gm"],
    "tempo": [155],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/thunderbolt",
    "art": "https://f4.bcbits.com/img/a4155316201_10.jpg",
  },
  {
    "id": 22,
    "title": "Cyber Talk",
    "subtitle": "",
    "release_date": "2016-10-24",
    "length": 258,
    "keysig": ["B / G#m"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-cyber-talk",
    "art": "https://f4.bcbits.com/img/a0384878721_10.jpg",
  },
  {
    "id": 23,
    "title": "Party",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2016-12-4",
    "length": 257,
    "keysig": ["A# / Gm"],
    "tempo": [128],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/party-remix",
    "art": "https://i1.sndcdn.com/artworks-000201109805-heszyu-original.jpg",
  },
  {
    "id": 24,
    "title": "Stay Classy",
    "subtitle": "w/ Redshift",
    "release_date": "2016-12-21",
    "length": 251,
    "keysig": ["D / Bm"],
    "tempo": [100],
    "label": "Independent",
    "remix": false,
    "collaboration": true,
    "link": "https://soundcloud.com/dreamscape_records/redshift-similar-outskirts-stay-classy",
    "art": "https://i1.sndcdn.com/artworks-000199509544-gocf3d-original.jpg",
  },
  {
    "id": 25,
    "title": "Aishiteru Banzai!",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-1-10",
    "length": 262,
    "keysig": ["E / C#m"],
    "tempo": [100],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts-extra/aishiteru-banzai-remix",
    "art": "https://i1.sndcdn.com/artworks-000202192302-2jtlvg-original.jpg",
  },
  {
    "id": 26,
    "title": "Nanamori",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-2-5",
    "length": 217,
    "keysig": ["A# / Gm"],
    "tempo": [160],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/nanamori-remix",
    "art": "https://i1.sndcdn.com/artworks-000206361585-o76n59-original.jpg",
  },
  {
    "id": 27,
    "title": "Starchaser",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-2-15",
    "length": 350,
    "keysig": ["D# / Cm"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/dreamscape_records/starchaser-similar-outskirts-remix",
    "art": "https://i1.sndcdn.com/artworks-000207914906-wpe4v0-original.jpg",
  },
  {
    "id": 28,
    "title": "Burnout",
    "subtitle": "",
    "release_date": "2017-3-7",
    "length": 293,
    "keysig": ["G# / Fm"],
    "tempo": [174],
    "label": "Umbra Collective",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/umbracollective/similar-outskirts-burnout",
    "art": "https://i1.sndcdn.com/artworks-000211074842-oekjck-original.jpg",
  },
  {
    "id": 29,
    "title": "Guilty Eyes Fever",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-4-13",
    "length": 299,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts-extra/guilty-eyes-fever-remix",
    "art": "https://i1.sndcdn.com/artworks-000217654503-mqffcv-original.jpg",
  },
  {
    "id": 30,
    "title": "No Stopping Us",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-5-28",
    "length": 262,
    "keysig": ["E / C#m"],
    "tempo": [160],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/no-stopping-us-remix",
    "art": "https://i1.sndcdn.com/artworks-000224736337-vmtyfc-original.jpg",
  },
  {
    "id": 31,
    "title": "Atlantis",
    "subtitle": "",
    "release_date": "2017-6-19",
    "length": 262,
    "keysig": ["A / F#m"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-atlantis",
    "art": "https://f4.bcbits.com/img/a4106883742_10.jpg",
  },
  {
    "id": 32,
    "title": "Phantom",
    "subtitle": "",
    "release_date": "2017-7-10",
    "length": 253,
    "keysig": ["F / Dm"],
    "tempo": [128],
    "label": "Rushdown",
    "remix": false,
    "collaboration": false,
    "link": "https://fanlink.tv/SimilarOutskirtsPhantom",
    "art": "https://i1.sndcdn.com/artworks-000232933218-ffbdjf-original.jpg",
  },
  {
    "id": 33,
    "title": "Our World",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-8-14",
    "length": 339,
    "keysig": ["D / Bm"],
    "tempo": [120],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/our-world-remix",
    "art": "https://i1.sndcdn.com/artworks-000238230107-oo7d27-original.jpg",
  },
  {
    "id": 34,
    "title": "Lonely Tuning",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-8-24",
    "length": 293,
    "keysig": ["D# / Cm"],
    "tempo": [100],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts-extra/lonely-tuning-remix",
    "art": "https://i1.sndcdn.com/artworks-000239720248-34b556-original.jpg",
  },
  {
    "id": 35,
    "title": "Wait For Me",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2017-9-1",
    "length": 300,
    "keysig": ["G / Em", "A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/wait-for-me-remix",
    "art": "https://i1.sndcdn.com/artworks-000240844547-41zu9t-original.jpg",
  },
  {
    "id": 36,
    "title": "Gadget",
    "subtitle": "",
    "release_date": "2017-10-13",
    "length": 325,
    "keysig": ["A / F#m"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://similaroutskirts.fanlink.tv/gadget",
    "art": "https://f4.bcbits.com/img/a2015114710_10.jpg",
  },
  {
    "id": 37,
    "title": "Daring!!",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2018-1-10",
    "length": 241,
    "keysig": ["F / Dm"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts-extra/daring-remix",
    "art": "https://i1.sndcdn.com/artworks-000283273985-xul607-t500x500.jpg",
  },
  {
    "id": 38,
    "title": "Daredevil",
    "subtitle": "",
    "release_date": "2018-2-23",
    "length": 317,
    "keysig": ["A# / Gm"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://similaroutskirts.fanlink.tv/daredevil-ep",
    "art": "https://f4.bcbits.com/img/a2842958488_10.jpg",
  },
  {
    "id": 39,
    "title": "Space Combat",
    "subtitle": "",
    "release_date": "2018-2-24",
    "length": 280,
    "keysig": ["G# / Fm"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://similaroutskirts.fanlink.tv/daredevil-ep",
    "art": "https://f4.bcbits.com/img/a2842958488_10.jpg",
  },
  {
    "id": 40,
    "title": "Triumphant",
    "subtitle": "",
    "release_date": "2018-2-25",
    "length": 266,
    "keysig": ["G# / Fm"],
    "tempo": [90],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://similaroutskirts.fanlink.tv/daredevil-ep",
    "art": "https://f4.bcbits.com/img/a2842958488_10.jpg",
  },
  {
    "id": 41,
    "title": "Street Race",
    "subtitle": "",
    "release_date": "2018-2-26",
    "length": 246,
    "keysig": ["G / Em"],
    "tempo": [160],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://similaroutskirts.fanlink.tv/daredevil-ep",
    "art": "https://f4.bcbits.com/img/a2842958488_10.jpg",
  },
  {
    "id": 42,
    "title": "Amber",
    "subtitle": "",
    "release_date": "2018-4-14",
    "length": 217,
    "keysig": ["D / Bm"],
    "tempo": [100],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://similaroutskirts.fanlink.tv/amber",
    "art": "https://f4.bcbits.com/img/a1482471213_10.jpg",
  },
  {
    "id": 43,
    "title": "HEROIC ADVENT",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2018-5-19",
    "length": 237,
    "keysig": ["G / Em"],
    "tempo": [182],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts-extra/heroic-advent-remix",
    "art": "https://i1.sndcdn.com/artworks-000478271904-2j4eds-original.jpg",
  },
  {
    "id": 44,
    "title": "Chaos",
    "subtitle": "",
    "release_date": "2018-6-8",
    "length": 256,
    "keysig": ["B / G#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://similaroutskirts.fanlink.tv/chaos",
    "art": "https://f4.bcbits.com/img/a2801167212_10.jpg",
  },
  {
    "id": 45,
    "title": "Xana",
    "subtitle": "",
    "release_date": "2018-7-27",
    "length": 247,
    "keysig": ["G# / Fm"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "collaboration": false,
    "link": "https://fanlink.tv/SOHorologyEP",
    "art": "https://i1.sndcdn.com/artworks-000380151171-3tuzlp-original.jpg",
  },
  {
    "id": 46,
    "title": "Horology",
    "subtitle": "",
    "release_date": "2018-8-5",
    "length": 280,
    "keysig": ["A# / Gm"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "collaboration": false,
    "link": "https://fanlink.tv/SOHorologyEP",
    "art": "https://i1.sndcdn.com/artworks-000383639997-6696qo-original.jpg",
  },
  {
    "id": 47,
    "title": "Time Leap",
    "subtitle": "",
    "release_date": "2018-8-5",
    "length": 294,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "collaboration": false,
    "link": "https://fanlink.tv/SOHorologyEP",
    "art": "https://i1.sndcdn.com/artworks-000383639997-6696qo-original.jpg",
  },
  {
    "id": 48,
    "title": "Hourglass",
    "subtitle": "",
    "release_date": "2018-8-6",
    "length": 319,
    "keysig": ["C / Am", "D / Bm"],
    "tempo": [150],
    "label": "Rushdown",
    "remix": false,
    "collaboration": false,
    "link": "https://fanlink.tv/SOHorologyEP",
    "art": "https://i1.sndcdn.com/artworks-000383639997-6696qo-original.jpg",
  },
]