export const MusicData = [
  {
    "id": 1,
    "title": "Technology",
    "subtitle": "",
    "release_date": "2014-4-19",
    "type": "single",
    "length": 286,
    "keysig": ["A / F#m"],
    "tempo": [175],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-technology",
    "art": "https://f4.bcbits.com/img/a2602584825_10.jpg",
  },
  {
    "id": 2,
    "title": "Feel The Buzz",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2014-7-19",
    "type": "single",
    "length": 252,
    "keysig": ["E / C#m"],
    "tempo": [105, 175],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/sub-sound-feel-the-buzz",
    "art": "https://i1.sndcdn.com/artworks-000201108064-pbjh4c-t200x200.jpg",
  },
  {
    "id": 3,
    "title": "Cyborg Meltdown",
    "subtitle": "",
    "release_date": "2014-7-21",
    "type": "single",
    "length": 259,
    "keysig": ["D / Bm"],
    "tempo": [110],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-cyborg",
    "art": "https://f4.bcbits.com/img/a1515047272_10.jpg",
  },
  {
    "id": 4,
    "title": "Boom!",
    "subtitle": "",
    "release_date": "2014-7-29",
    "type": "single",
    "length": 217,
    "keysig": ["C / Am"],
    "tempo": [130],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-boom-the",
    "art": "https://i1.sndcdn.com/artworks-000201108332-a1a4c1-t200x200.jpg",
  },
  {
    "id": 5,
    "title": "Snowball Fight",
    "subtitle": "",
    "release_date": "2014-8-18",
    "type": "single",
    "length": 232,
    "keysig": ["G / Em"],
    "tempo": [175],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-snowball-fight",
    "art": "https://i1.sndcdn.com/artworks-000201108469-ewix52-t200x200.jpg",
  },
  {
    "id": 6,
    "title": "Jubilant Skydive",
    "subtitle": "",
    "release_date": "2014-9-15",
    "type": "single",
    "length": 264,
    "keysig": ["F / Dm", "G / Em"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-jubilant",
    "art": "https://i1.sndcdn.com/artworks-000201108577-7ke5xc-t200x200.jpg",
  },
  {
    "id": 7,
    "title": "Interstellar",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2014-11-2",
    "type": "single",
    "length": 206,
    "keysig": ["G / Em"],
    "tempo": [170],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/laszlo-interstellar-similar",
    "art": "https://i1.sndcdn.com/artworks-000201108680-1972jr-t200x200.jpg",
  },
  {
    "id": 8,
    "title": "Radiation",
    "subtitle": "",
    "release_date": "2014-11-21",
    "type": "single",
    "length": 248,
    "keysig": ["C / Am"],
    "tempo": [174],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-radiation",
    "art": "https://i1.sndcdn.com/artworks-000201108735-zomr6p-t200x200.jpg",
  },
  {
    "id": 9,
    "title": "When You Sleep",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2014-12-23",
    "type": "single",
    "length": 211,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/vau-boy-when-you-sleep-2014-ft",
    "art": "https://i1.sndcdn.com/artworks-000201108789-sbmywn-t200x200.jpg",
  },
]