export const MusicData = [
  {
    "id": 1,
    "title": "Technology",
    "subtitle": "",
    "release_date": "2014-4-19",
    "type": "single",
    "length": 286,
    "keysig": ["A / F#m"],
    "tempo": [175],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-technology",
    "art": "https://f4.bcbits.com/img/a2602584825_10.jpg",
  },
  {
    "id": 2,
    "title": "Feel The Buzz",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2014-7-19",
    "type": "single",
    "length": 252,
    "keysig": ["E / C#m"],
    "tempo": [105, 175],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/sub-sound-feel-the-buzz",
    "art": "https://i1.sndcdn.com/artworks-000201108064-pbjh4c-original.jpg",
  },
  {
    "id": 3,
    "title": "Cyborg Meltdown",
    "subtitle": "",
    "release_date": "2014-7-21",
    "type": "single",
    "length": 259,
    "keysig": ["D / Bm"],
    "tempo": [110],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-cyborg",
    "art": "https://f4.bcbits.com/img/a1515047272_10.jpg",
  },
  {
    "id": 4,
    "title": "Boom!",
    "subtitle": "",
    "release_date": "2014-7-29",
    "type": "single",
    "length": 217,
    "keysig": ["C / Am"],
    "tempo": [130],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-boom-the",
    "art": "https://f4.bcbits.com/img/a2416192760_10.jpg",
  },
  {
    "id": 5,
    "title": "Snowball Fight",
    "subtitle": "",
    "release_date": "2014-8-18",
    "type": "single",
    "length": 232,
    "keysig": ["G / Em"],
    "tempo": [175],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-snowball-fight",
    "art": "https://f4.bcbits.com/img/a3465120814_10.jpg",
  },
  {
    "id": 6,
    "title": "Jubilant Skydive",
    "subtitle": "",
    "release_date": "2014-9-15",
    "type": "single",
    "length": 264,
    "keysig": ["F / Dm", "G / Em"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-jubilant",
    "art": "https://f4.bcbits.com/img/a2758000269_10.jpg",
  },
  {
    "id": 7,
    "title": "Interstellar",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2014-11-2",
    "type": "single",
    "length": 206,
    "keysig": ["G / Em"],
    "tempo": [170],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/laszlo-interstellar-similar",
    "art": "https://i1.sndcdn.com/artworks-000201108680-1972jr-original.jpg",
  },
  {
    "id": 8,
    "title": "Radiation",
    "subtitle": "",
    "release_date": "2014-11-21",
    "type": "single",
    "length": 248,
    "keysig": ["C / Am"],
    "tempo": [174],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/similar-outskirts-radiation",
    "art": "https://f4.bcbits.com/img/a4080141869_10.jpg",
  },
  {
    "id": 9,
    "title": "When You Sleep",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2014-12-23",
    "type": "single",
    "length": 211,
    "keysig": ["A / F#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/vau-boy-when-you-sleep-2014-ft",
    "art": "https://i1.sndcdn.com/artworks-000201108789-sbmywn-original.jpg",
  },
  {
    "id": 10,
    "title": "I'm Here",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2015-6-12",
    "type": "single",
    "length": 208,
    "keysig": ["B / G#m"],
    "tempo": [170],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/im-here-remix",
    "art": "https://i1.sndcdn.com/artworks-000201108920-ha9ybf-original.jpg",
  },
  {
    "id": 11,
    "title": "The Time Traveller",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2015-12-12",
    "type": "single",
    "length": 235,
    "keysig": ["A / F#m"],
    "tempo": [140, 175],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/getsix-the-time-traveller-similar-outskirts-remix",
    "art": "https://i1.sndcdn.com/artworks-000201109218-vmy3sr-original.jpg",
  },
  {
    "id": 12,
    "title": "Epiphany",
    "subtitle": "",
    "release_date": "2015-12-31",
    "type": "single",
    "length": 221,
    "keysig": ["A / F#m"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/epiphany",
    "art": "https://f4.bcbits.com/img/a4246737652_10.jpg",
  },
  {
    "id": 13,
    "title": "Senses Overload",
    "subtitle": "Similar Outskirts Remix",
    "release_date": "2016-1-23",
    "type": "single",
    "length": 259,
    "keysig": ["F# / D#m"],
    "tempo": [174],
    "label": "Independent",
    "remix": true,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/senses-overload-remix",
    "art": "https://i1.sndcdn.com/artworks-000201109366-dwo6l9-original.jpg",
  },
  {
    "id": 14,
    "title": "Blast Off",
    "subtitle": "",
    "release_date": "2016-2-13",
    "type": "single",
    "length": 214,
    "keysig": ["C / Am"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/blast-off",
    "art": "https://f4.bcbits.com/img/a0732027681_10.jpg",
  },
  {
    "id": 15,
    "title": "No Limits EP",
    "subtitle": "",
    "release_date": "2016-5-7",
    "type": "ep",
    "length": 0,
    "keysig": ["-"],
    "tempo": [0],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/similar-outskirts/sets/no-limits-ep-out-now",
    "art": "https://f4.bcbits.com/img/a2071563971_10.jpg",
  },
  {
    "id": 16,
    "title": "Choreography",
    "subtitle": "",
    "release_date": "2016-5-7",
    "type": "single",
    "length": 273,
    "keysig": ["D / Bm"],
    "tempo": [145],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-choreography-1",
    "art": "https://f4.bcbits.com/img/a2071563971_10.jpg",
  },
  {
    "id": 17,
    "title": "Whiplash",
    "subtitle": "",
    "release_date": "2016-5-7",
    "type": "single",
    "length": 229,
    "keysig": ["B / G#m"],
    "tempo": [150],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-whiplash-1",
    "art": "https://f4.bcbits.com/img/a2071563971_10.jpg",
  },
  {
    "id": 18,
    "title": "Awake and Unafraid",
    "subtitle": "",
    "release_date": "2016-5-7",
    "type": "single",
    "length": 227,
    "keysig": ["A / F#m"],
    "tempo": [128],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-awake-and-unafraid",
    "art": "https://f4.bcbits.com/img/a2071563971_10.jpg",
  },
  {
    "id": 19,
    "title": "Roller Coaster",
    "subtitle": "",
    "release_date": "2016-5-7",
    "type": "single",
    "length": 262,
    "keysig": ["A / F#m"],
    "tempo": [170],
    "label": "Independent",
    "remix": false,
    "collaboration": false,
    "link": "https://soundcloud.com/dreamscape_records/similar-outskirts-roller-coaster",
    "art": "https://f4.bcbits.com/img/a2071563971_10.jpg",
  },
]