import React from "react";
import PageTitle from "../components/PageTitle";

function MusicUsage() {
  return (
    <>
      {/* Background */}
      <div
        className="h-screen w-screen bg-show4 fixed -z-50
                   bg-cover bg-no-repeat bg-[70%] md:bg-center"
      />
      <div className="w-[64rem] grid place-items-center animate-fadeInSlide mb-16">
        {/* Title */}
        <PageTitle title={"Music Usage"} />

        {/* General Info */}
        <div className="my-12 text-justify text-lg w-[64rem] space-y-8 justify-center">
          <h2 className="font-bold text-5xl">General Info</h2>
          <p>
            My music is available to be used in your YouTube and Twitch content,
            many of which come with certain restrictions.
          </p>
          <p>
            One particular restriction involves YouTube content ID, which allows
            me to prevent a YouTube video from being monetizable by the channel
            if it detects my music within it. Instead, all ad revenue that would
            be generated by the video goes to me. This does not harm your
            channel, and you will not receive a copyright strike or anything
            similar unless my music is being used maliciously (fraud, theft,
            etc).
          </p>
          <p>
            Visit my music page, which lists my entire discography and how you
            may use each track in your online content!
          </p>
          <p>
            If you would like to use my music for commercial use (film,
            advertising, TV, video games, etc) or if you are unclear about
            anything, please feel free to contact me. Please describe your
            request in detail.
          </p>
        </div>

        <span className="w-96 h-[1px] bg-gray-500 my-8" />

        {/* How To Credit */}
        <div className="my-12 text-justify text-lg w-[64rem] space-y-8">
          <h2 className="font-bold text-5xl">How To Credit</h2>
          <p>
            You can credit me by putting the following in the description of
            your video/stream:
          </p>
          <div
            className="p-8 w-[30rem]
                        border-4 border-slate-800 bg-slate-900 bg-opacity-90 backdrop-blur"
          >
            <code>
              <p>Music by Similar Outskirts:</p>
              <p>https://similaroutskirts.com</p>
              <p>https://soundcloud.com/similar-outskirts</p>
              <p>https://x.com/Sim_Out_</p>
              <p>https://youtube.com/SimilarOutskirts</p>
            </code>
          </div>
        </div>

        <span className="w-96 h-[1px] bg-gray-500 my-8" />

        {/* Custom Maps/Charts for Rhythm Games */}
        <div className="my-12 text-justify text-lg w-[64rem] space-y-8">
          <h2 className="font-bold text-5xl">
            Custom Maps/Charts for Rhythm Games
          </h2>
          <p>
            Feel free to make custom rhythm game maps/charts in the following
            games. These should be fan-made. Commercial use is NOT allowed. If
            you are a developer looking to officially release my music along
            with a map/chart in your game, feel free to contact me.
          </p>
          <div
            className="p-8 w-[30rem]
                            border-4 border-slate-800 bg-slate-900 bg-opacity-90 backdrop-blur"
          >
            <code>
              <p>- A Dance of Fire and Ice</p>
              <p>- Clone Hero</p>
              <p>- osu!</p>
              <p>- Project Arrythmia</p>
              <p>- Rhythm Doctor</p>
              <p>- Soundodger 2</p>
            </code>
          </div>
        </div>

        <span className="w-96 h-[1px] bg-gray-500 my-8" />

        {/* FAQ */}
        <div className="my-12 text-justify text-lg w-[64rem] space-y-8">
          <h2 className="font-bold text-5xl">FAQ</h2>
        </div>
      </div>
    </>
  );
}

export default MusicUsage;
